version: 1

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
brews:
  - repository:
      owner: mikesmithgh
      name: homebrew-git-prompt-string
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Formula
    goarm: "7"
    homepage: https://github.com/mikesmithgh/git-prompt-string
    description: "A shell agnostic git prompt written in Go"
    license: "Apache-2.0"
    test: |
      system "#{bin}/git-prompt-string --version"
    dependencies:
      - name: git

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
