#!/bin/bash
#
# TODO add description

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$script_dir/bgps-config"
source "$script_dir/bgps-prompt"

bgps_config_file="${HOME}/.bgps_config"

# TODO implement flags better than this
if [[ $1 == "--ls-config" ]] ; then
  _print_config
elif [[ $1 == "--clear-config" ]] ; then
  _delete_config
else
  _set_config $bgps_config_file
  _bgps_prompt
fi

# clean up
_bgps_config_unset
_bgps_prompt_unset
unset bgps_config_file
unset script_dir
